spring.application.name=tracking


kafka.bootstrap-servers=172.18.214.147:9092


#doesn't work this solution:
#spring.kafka.consumer.properties.spring.json.value.default.type=dev.vilelo.tracking.message.OrderTracked
#spring.kafka.consumer.properties.spring.json.trusted.packages=*
#spring.kafka.consumer.properties.spring.json.remove.type.headers=true